title: Adelos Labs
description: Resources for using one-time pads.
theme: jekyll-theme-hacker

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default
